learning_log/urls.py
"""learning_log"""
from django.contrib import admin
from django.urls import path, include,re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls', namespace='learning_logs')),
    re_path(r'^users/',include('users.urls',namespace = 'users')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""

from django.urls import path, re_path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    # /()/中的()表示捕获正则数据，
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    path('new_topic/',views.new_topic,name='new_topic'),
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry,
            name='edit_entry'),
]

users/urls.py
"""定义users的URL模式"""
"""为应用程序users定义URL模式"""
# users/urls.py
from django.urls import path,re_path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'urls'
urlpatterns = [
    # 登录页面
    path('login/', LoginView.as_view(template_name='users/login.html'),
            name='login'),
    re_path(r'^logout/$', views.logout_view, name='logout'),
    re_path(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#Just 模型告诉Django如何处理程序中存储的数据
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    #https://docs.djangoproject.com/en/1.8/ref/models/fields
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text
class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        #https://docs.djangoproject.com/en/5.0/
        if len(self.text)<50:
            return self.text
        return self.text[:50]+"..."









    

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        # 最简单的ModelForm版本只包含一个内嵌的Meta类，
        # 它告诉Django根据哪个模型创建表单，
        # 以及在表单中包含哪些字段。
        # 我们根据模型Topic创建一个表单，
        # 该表单只包含字段text
        model = Topic
        fields = ['text']
        labels = {'text': ''}  # 让Django不要为字段text生成标签。

class EntryForm(forms.ModelForm):
   class Meta:
       model = Entry
       fields = ['text']
       labels = {'text': ''}
        # 小部件（widget）是一个HTML表单元素，如单行文本框、多行文本区域或下拉列表。
        # 通过设置属性widgets，可覆盖Django选择的默认小部件。
        # 通过让Django使用forms.Textarea，我们定制了字段text的输入小部件，将文本区域的宽度设置为80列，而不是默认的40列。
        # 这给用户提供了足够的空间，可以编写有意义的条目
       widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from .models import Topic,Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    """
    显示所有的主题
    """
    topics = Topic.objects.order_by('date_added')
    # 上下文是一个字典，其中的键是我们将在模板中用来访问数据的名称，
    # 而值是我们要发送给模板的数据。
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'toplist':topics}
    return render(request,'learning_logs/topics.html',context)
@login_required
def topic(request,topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')#-表示按降序排列，即先显示最近的条目
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)
@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据,对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():#判断用户填写是否有效
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)
@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # 未提交数据,创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)
@login_required
def edit_entry(request,entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method !='POST':
        #初次请求，使用当前条目填充表单
        form = EntryForm(instance = entry)
    else:
        #POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout,login, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))
def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)  # 更新login的使用方式
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
{#    <a href="{% url 'learning_logs:topics' %}">Topics</a>#}
    <a href="{% url 'learning_logs:topics' %}">Topics</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a> -
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
 <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

 <p>Edit entry:</p>

 <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
 {% csrf_token %}
 {{ form.as_p }}
 <button name="submit">save changes</button>
 </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Learning Log helps you keep track of your learning, for any topic you'relearning about.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>add entry</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add topic</button>
    </form>

{% endblock %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html'%}

{% block content %}
	<p>Topic: {{ topic }}</p>

    <p>Entries:</p>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    </p>
    <ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d,Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
            <p>
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
            </p>
        </li>
    {% empty %}
        <li>
            There are no entries for this topic yet.
        </li>
    {% endfor %}
    </ul>

{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% for topic in toplist %}

{% empty %}

{% endfor %}


{% block content %}
    <p>Topics</p>

    <ul>
        {% for topic in toplist %}
{#            <li>{{ topic }}</li>#}
            <li>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
 <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
 {% if form.errors %}
 <p>Your username and password didn't match. Please try again.</p>
 {% endif %}

 <form method="post" action="{% url 'users:login' %}">
 {% csrf_token %}
 {{ form.as_p }}

 {% buttons %}
 <button name="submit" class="btn btn-primary">log in</button>
 {% endbuttons %}
 <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
 </form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% block content %}
 <form method="post" action="{% url 'users:register' %}">
 {% csrf_token %}
 {{ form.as_p }}

 <button name="submit">register</button>
 <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
 </form>

{% endblock content %}